Admin servlets & jsp
mashinasystem/mashina pull request #22
Opened 2019-04-29 18:59 UTC by iaramer

Add admin servlets, order servlets and jsps for them

IF YOU WANNA GO TO ADMIN PAGE:
1. Go to login page
2. On the top left corner press on "Admin page"
3. Congrats! You can discover the admin pages

2019-04-29 21:53 UTC, goponenkoev approved these changes

2019-04-29 22:06 UTC, DeryckSPBU requested changes

2019-04-29 22:06 UTC, DeryckSPBU commented on src/main/java/com/epam/machine/controller/AdminCertainOrderServlet.java
> +            request.setAttribute("fail", 0);
Why is it everywhere in our servlets, is it really necessary?

2019-04-29 22:06 UTC, DeryckSPBU commented on src/main/resources/messages.properties
> +label.customers=Customers
Since we have i18n implemented, you should internationalise your JSPs, pay attention to possiible duplicates

2019-04-30 16:42 UTC, DeryckSPBU approved these changes

2019-05-01 20:44 UTC, iaramer commented on src/main/java/com/epam/machine/controller/AdminCertainOrderServlet.java
> +            request.setAttribute("fail", 0);
What exactly?

2019-05-01 20:44 UTC, iaramer commented on src/main/resources/messages.properties
> +label.customers=Customers
I know about that. This field was added only for temporary use.

2019-05-01 20:45 UTC, merged